package constants 

type Prompt string
type Path string

const(
	ViewResidentPrompt Prompt = "View All Residents"
	ViewOfficersPrompt Prompt = "View All Officers"
	LogoutPrompt Prompt  = "Logout"
	SignUpPrompt Prompt = "Sign Up"
	LoginPrompt Prompt = "Login"
	ExitPrompt Prompt = "Exit\n\n"
	FirstNamePrompt Prompt = "First Name"
	MiddleNamePrompt Prompt = "Middle Name (optional):"
	LastNamePrompt Prompt = "Last Name"
	EmailPrompt Prompt = "Email/ID"
	MobilePrompt Prompt = "Mobile Number"
	IDPrompt Prompt = "ID (Username): "
	PasswordPrompt Prompt = "Password: "
	ConfirmPasswordPrompt Prompt = "Confirm Password: "
	RolePrompt Prompt= "Role (Admin / MaintenanceOfficer / FlatResident)"
	ChoicePrompt Prompt = "Enter your choice: "
	SignUpEmogiPrompt Prompt = "📝                                                📝"
	LoginEmogiPrompt Prompt = "🧑‍💻                                          🧑‍💻"
	AppEmogiPrompt Prompt = "🛠️                                                 🛠️"
	AdminEmogiPrompt Prompt = "🔐                                       🔐"
	OfficerEmogiPrompt Prompt = "👨‍💼                                            👨‍💼"
	ResidentEmogiPrompt Prompt = "👨‍👩‍👧‍👦                                               👨‍👩‍👧‍👦"
	DeleteResidentPrompt Prompt = "Delete Resident Credentials"
	DeleteOfficerPrompt Prompt = "Delete Officer Credentials"
	IssueNoticePrompt Prompt = "Issue Notice"
	GetNoticePrompt Prompt = "Get Notices"
	GetNoticesByMonthYear Prompt = "Get notices by month and year"
	GetNoticesByYear Prompt = "Get notices by year"
	CreateServiceRequestPrompt Prompt = "Create Service Request"
	CancelServiceRequestPrompt Prompt = "Cancel Service Request"
	ApproveServiceRequestPrompt Prompt = "Approve Service Request"
	RescheduleServiceRequestPrompt Prompt = "Reschedule Service Request"
	GetPendingServiceRequestPrompt Prompt = "View Pending Service Requests"
	GetApprovedServiceRequestPrompt Prompt = "View Approved Service Requests"
	GiveFeedbackPrompt Prompt = "Give Feedback"
	GetAllFeedbackPrompt Prompt = "View all Feedbacks"
	GetFeedbacksByID Prompt = "View Feedbacks of a Resident"
	UpdateProfilePrompt Prompt = "Update Profile"
	ChangePasswordPrompt Prompt = "Change Password"
	AddOfficerPrompt Prompt = "Add a Officer"
	GetFeedbackForResident = "View given feedbacks"
	IssueInvoice Prompt = "Issue Invoice"
	SearchAInvoice = "Search a Invoice"
	ListInvoicesOfAYear = "Search invoices of a Year"
	DeleteProfilePrompt = "Delete Profile"
	ViewProfilePrompt = "View Profile"
	NoticeFormatPrompt = "ID: %s\t|\tDate: %s\nContent: \n %s\n\n"
	SerivceFormatPrompt = "RequestID: %s Service Type: %s | ResidentID: %s | TimeSlot: %s | Status: %s\n\n"
	FeedbackFormatPrompt = "ResidentID: %s | Rating: %d\nContent:-\n%s\n\n"
	InvoiceFormatPrompt = "InvoiceID: %s | Amount: %f | Month: %s | Year: %s\n\n"
	MainDataPath Path = "../../data"
	UserDataPath Path = MainDataPath + "/users.json" 
	NoticeDataPath Path = MainDataPath + "/notices.json"
	ServiceRequestDataPath Path = MainDataPath + "/service_request.json"
	FeedbackDataPath Path= MainDataPath + "/feedback.json"
	InvoiceDataPath Path = MainDataPath + "/invoices.json"
	StartTimeOfService = 9
	EndTimeOfService = 17
	TimeLimitOfSlot = 45
	TimeLayout = "15:04"

)